version: "3.8"

volumes:
  carcosa-volume:
  character-volume:
  summon-volume:


services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf.dev:/etc/nginx/conf.d/default.conf:ro
      - carcosa-volume:/usr/share/nginx/html/carcosa
      - character-volume:/usr/share/nginx/html/character
      - summon-volume:/usr/share/nginx/html/summon
    depends_on:
      - funkaoshi-randomcharacter
      - funkaoshi-lotfp-summon
      - funkaoshi-randomcarcosa

  funkaoshi-randomcharacter:
    image: funkaoshi/randomcharacter:latest
    volumes:
      - character-volume:/app/static
    ports:
      - 8000
    restart: unless-stopped

  funkaoshi-lotfp-summon:
    image: funkaoshi/lotfp-summon:latest
    volumes:
      - summon-volume:/app/static
    ports:
      - 8001
    restart: unless-stopped

  funkaoshi-randomcarcosa:
    image: funkaoshi/randomcarcosa:latest
    volumes:
      - carcosa-volume:/app/static
    ports:
      - 8002
    restart: unless-stopped

  linkding:
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env-linkding
    restart: unless-stopped
